// sites/rxlens/src/components/report-pdf-document.tsx

import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'

import type { PgxReport } from '@/lib/pgx-types'

const styles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1f2937',
  },
  title: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 10,
    marginBottom: 14,
    color: '#4b5563',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#e5e7eb',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    paddingVertical: 6,
    paddingHorizontal: 4,
    fontWeight: 700,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  colGene: {
    width: '14%',
    paddingRight: 4,
  },
  colDiplotype: {
    width: '15%',
    paddingRight: 4,
  },
  colPhenotype: {
    width: '22%',
    paddingRight: 4,
  },
  colDrugs: {
    width: '24%',
    paddingRight: 4,
  },
  colRecommendation: {
    width: '25%',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 8,
  },
  technicalCard: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
  },
  technicalGene: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 4,
  },
  bodyLine: {
    marginBottom: 2,
    lineHeight: 1.4,
  },
  disclaimerBox: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#9ca3af',
    padding: 8,
    borderRadius: 6,
  },
  small: {
    fontSize: 9,
    color: '#374151',
    lineHeight: 1.4,
  },
})

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

interface ReportPdfDocumentProps {
  report: PgxReport
}

export function ReportPdfDocument({ report }: ReportPdfDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>
          Pharmacogenomic Report - Generated by RxLens
        </Text>
        <Text style={styles.subtitle}>
          Date: {formatDate(report.generatedAtIso)} | Data source:{' '}
          {report.source}
        </Text>

        <View style={styles.tableHeader}>
          <Text style={styles.colGene}>Gene</Text>
          <Text style={styles.colDiplotype}>Diplotype</Text>
          <Text style={styles.colPhenotype}>Phenotype</Text>
          <Text style={styles.colDrugs}>Key Affected Drugs</Text>
          <Text style={styles.colRecommendation}>CPIC Recommendation</Text>
        </View>

        {report.geneReports.map((gene) => (
          <View style={styles.tableRow} key={gene.gene}>
            <Text style={styles.colGene}>{gene.gene}</Text>
            <Text style={styles.colDiplotype}>{gene.diplotype}</Text>
            <Text style={styles.colPhenotype}>{gene.phenotype}</Text>
            <Text style={styles.colDrugs}>{gene.affectedDrugs.join(', ')}</Text>
            <Text style={styles.colRecommendation}>
              {gene.cpicRecommendation}
            </Text>
          </View>
        ))}

        <View style={styles.disclaimerBox}>
          <Text style={styles.small}>
            Based on CPIC Level A guidelines. This is not a diagnostic test.
            This report is not medical advice.
          </Text>
          <Text style={styles.small}>
            Do not change medication without consulting a licensed healthcare
            provider.
          </Text>
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Technical Details</Text>

        {report.geneReports.map((gene) => (
          <View key={gene.gene} style={styles.technicalCard}>
            <Text style={styles.technicalGene}>
              {gene.gene} - {gene.diplotype} ({gene.phenotype})
            </Text>
            {gene.rawCalls.map((call) => (
              <Text key={call.rsid} style={styles.bodyLine}>
                {call.rsid}: {call.genotype ?? 'No-call'} -{' '}
                {call.interpretation}
              </Text>
            ))}
            <Text style={styles.bodyLine}>
              Coverage: {gene.coverage.genotyped}/{gene.coverage.total} loci
              genotyped
            </Text>
            {gene.coverage.missingRsids.length > 0 ? (
              <Text style={styles.bodyLine}>
                Missing loci: {gene.coverage.missingRsids.join(', ')}
              </Text>
            ) : null}
            {gene.notes.map((note) => (
              <Text key={note} style={styles.bodyLine}>
                Note: {note}
              </Text>
            ))}
          </View>
        ))}

        <View style={styles.disclaimerBox}>
          <Text style={styles.small}>
            Known limitations of array-based calling:
          </Text>
          <Text style={styles.small}>
            - Consumer SNP arrays do not capture all pharmacogene variants.
          </Text>
          <Text style={styles.small}>
            - CYP2D6 copy-number changes (duplications/deletions) are not
            resolved.
          </Text>
          <Text style={styles.small}>
            - HLA tag SNPs are proxies and may require confirmatory clinical
            testing.
          </Text>
          <Text style={styles.small}>
            - Not evaluated by FDA; intended for clinician discussion support.
          </Text>
        </View>
      </Page>
    </Document>
  )
}
